development:
  adapter: postgresql
  encoding: utf8
  database: yelp_challenge_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: yelp_challenge_test
  pool: 5
  username:
  password:
